// Regenerates src/comment/youtube-emoji.js from the emoji list YouTube's live chat loads (the chat page's
// config points to it). Run: node scripts/update-emoji.js [url]
import fs from 'node:fs';
import path from 'node:path';
import { emojiCode } from '../src/comment/emoji.js';

const url = process.argv[2] ?? 'https://www.gstatic.com/youtube/img/emojis/emojis-png-15.1.json';
const version = url.match(/emojis-png-([\d.]+)\.json/)?.[1] ?? '?';
const list = await (await fetch(url)).json();

const codes = list.filter((emoji) => !emoji.isCustomEmoji).map((emoji) => {
  const code = emojiCode(emoji.emojiId);
  // The app derives each image URL from the code; stop if YouTube's list ever names one differently.
  if (!emoji.image.thumbnails[0].url.endsWith(`/notoemoji/${version}/${code}/72.png`)) {
    throw new Error(`Unexpected image URL for ${code}: ${emoji.image.thumbnails[0].url}`);
  }
  return code;
});

const lines = [];
for (let i = 0; i < codes.length; i += 12) lines.push(codes.slice(i, i + 12).join(' '));
const source = `// YouTube's live-chat emoji set: the ${codes.length} emoji of ${url}
// (the list YouTube's chat loads), as Noto code points. Generated by scripts/update-emoji.js; don't edit.
export const YOUTUBE_EMOJI_VERSION = '${version}';

export const YOUTUBE_EMOJI_CODES = \`
${lines.join('\n')}
\`;
`;
const target = path.join(import.meta.dirname, '..', 'src', 'comment', 'youtube-emoji.js');
fs.writeFileSync(target, source);
console.log(`Wrote ${codes.length} emoji (${version}) to ${path.relative(process.cwd(), target)}`);
